id: build_your_first_quest_add_quest_metadata
learningObjectives:
  - Get to know our integration with GitHub
hints:
  - "Make sure you've changed the title and description of the quest in the quest.yml file."
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "Now that we have merged your PR, the quest has been created. You can see it on our [Quest Builder page](${platform.baseUrl}/quest-builder)."
            delay: 2000
          - text: "There are a couple of things you can do there: upload a new version, test the quest (don't do it now), or delete the quest."
            delay: 2000
          - text: "As you can see on the page, the title and description have placeholder texts. Let's change that!"
            delay: 2000
          - text: "To change the title and the description, :instruction[please edit the quest.yml file.]"
            delay: 2000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: head-of-rd
                message: "Reviewing this right now, let's see..."
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: "Got your PR, going over it right now."
                    delay: 100
        github_pr_workflow_complete_success:
          if:
            conditions:
              - conditionId: github_does_file_contain
                equals: false
                params:
                  fileName: 'quest.yml'
                  regex: 'description: "Lorem ipsum'
              - conditionId: github_does_file_contain
                equals: false
                params:
                  fileName: 'quest.yml'
                  regex: 'title: Lorem ipsum'
            then:
              do:
                - actionId: bot_message
                  params:
                    person: head-of-rd
                    messages:
                      - text: "Seems good to me, go ahead and merge this PR."
                        delay: 1500
                - actionId: github_pr_approve
                  params:
                    person: head-of-rd
                    message: "Seems good to me, go ahead and merge this PR."
            else:
              do:
                - actionId: bot_message
                  params:
                    person: head-of-rd
                    messages:
                      - text: "I don't see that the title and the description were changed in quest.yml. Can you please change them both?"
                        delay: 2000
                - actionId: github_pr_reject
                  params:
                    person: head-of-rd
                    message: "I don't see that the title and the description were changed in quest.yml. Can you please change them both?"
        github_pr_merged:
          do:
            - actionId: finish_step
