id: build_your_first_quest_trigger_demo
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Hello world"
            delay: 2000
trigger:
  type: user_message
  params:
    person: keen
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: keen
          messages:
            - text: "Thanks for the reply"
              delay: 2000
      - actionId: finish_step
